# Generated by Django 4.1.13 on 2024-02-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnApp', '0002_category_register_details_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('noofdays', models.PositiveIntegerField()),
                ('options', models.JSONField()),
                ('rentalOptions', models.JSONField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnApp.category')),
            ],
        ),
    ]
